[2024-10-25T18:15:24.935+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: temp_data_pipeline_dag.track_data_task manual__2024-10-25T18:15:20.350160+00:00 [queued]>
[2024-10-25T18:15:24.940+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: temp_data_pipeline_dag.track_data_task manual__2024-10-25T18:15:20.350160+00:00 [queued]>
[2024-10-25T18:15:24.940+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-25T18:15:24.940+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-10-25T18:15:24.940+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-25T18:15:24.946+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): track_data_task> on 2024-10-25 18:15:20.350160+00:00
[2024-10-25T18:15:24.958+0000] {standard_task_runner.py:55} INFO - Started process 134 to run task
[2024-10-25T18:15:24.960+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'temp_data_pipeline_dag', 'track_data_task', 'manual__2024-10-25T18:15:20.350160+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/temp-***.py', '--cfg-path', '/tmp/tmpawsa6gdn']
[2024-10-25T18:15:24.961+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask track_data_task
[2024-10-25T18:15:24.994+0000] {task_command.py:388} INFO - Running <TaskInstance: temp_data_pipeline_dag.track_data_task manual__2024-10-25T18:15:20.350160+00:00 [running]> on host 53d4ed596613
[2024-10-25T18:15:25.039+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=santosh
AIRFLOW_CTX_DAG_ID=temp_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=track_data_task
AIRFLOW_CTX_EXECUTION_DATE=2024-10-25T18:15:20.350160+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-25T18:15:20.350160+00:00
[2024-10-25T18:15:25.040+0000] {logging_mixin.py:137} INFO - Directory data/raw does not exist.
[2024-10-25T18:15:25.040+0000] {logging_mixin.py:137} INFO - Directory data/processed does not exist.
[2024-10-25T18:15:25.040+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-10-25T18:15:25.045+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=temp_data_pipeline_dag, task_id=track_data_task, execution_date=20241025T181520, start_date=20241025T181524, end_date=20241025T181525
[2024-10-25T18:15:25.061+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-10-25T18:15:25.072+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
