[2024-10-25T16:30:51.548+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: temp_data_pipeline_dag.scrape_task scheduled__2024-10-24T00:00:00+00:00 [queued]>
[2024-10-25T16:30:51.558+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: temp_data_pipeline_dag.scrape_task scheduled__2024-10-24T00:00:00+00:00 [queued]>
[2024-10-25T16:30:51.558+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-25T16:30:51.558+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-10-25T16:30:51.559+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-25T16:30:51.567+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): scrape_task> on 2024-10-24 00:00:00+00:00
[2024-10-25T16:30:51.626+0000] {standard_task_runner.py:55} INFO - Started process 130 to run task
[2024-10-25T16:30:51.631+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'temp_data_pipeline_dag', 'scrape_task', 'scheduled__2024-10-24T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/temp-***.py', '--cfg-path', '/tmp/tmpj9lm3zrf']
[2024-10-25T16:30:51.637+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask scrape_task
[2024-10-25T16:30:51.684+0000] {task_command.py:388} INFO - Running <TaskInstance: temp_data_pipeline_dag.scrape_task scheduled__2024-10-24T00:00:00+00:00 [running]> on host 97df66c4b684
[2024-10-25T16:30:51.734+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=santosh
AIRFLOW_CTX_DAG_ID=temp_data_pipeline_dag
AIRFLOW_CTX_TASK_ID=scrape_task
AIRFLOW_CTX_EXECUTION_DATE=2024-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-24T00:00:00+00:00
[2024-10-25T16:30:51.735+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: scrape_and_save() missing 1 required positional argument: 'urls'
[2024-10-25T16:30:51.749+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=temp_data_pipeline_dag, task_id=scrape_task, execution_date=20241024T000000, start_date=20241025T163051, end_date=20241025T163051
[2024-10-25T16:30:51.781+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 15 for task scrape_task (scrape_and_save() missing 1 required positional argument: 'urls'; 130)
[2024-10-25T16:30:51.810+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-25T16:30:51.826+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
